# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Virtue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('personal_image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('personal_description', models.TextField()),
                ('quote', models.TextField()),
                ('personal_quote', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtues', to='registration.User')),
            ],
        ),
        migrations.CreateModel(
            name='VirtueEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtue_entries', to='registration.User')),
                ('virtue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtue_entries', to='checklist.Virtue')),
            ],
        ),
        migrations.CreateModel(
            name='VirtueSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtue_sets', to='registration.User')),
            ],
        ),
        migrations.AddField(
            model_name='virtue',
            name='virtue_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtues', to='checklist.VirtueSet'),
        ),
    ]
