# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='virtue',
            name='personal_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtue',
            name='personal_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='virtue',
            name='personal_quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtue',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
