# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20170424_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtueentry',
            name='date',
            field=models.DateTimeField(unique_for_date=True),
        ),
    ]
