# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_virtueset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='virtue',
            name='virtue_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtues', to='checklist.VirtueSet'),
        ),
        migrations.AlterField(
            model_name='virtueentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtue_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='virtueentry',
            name='virtue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtue_entries', to='checklist.Virtue'),
        ),
        migrations.AlterField(
            model_name='virtueset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtue_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
