# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20170419_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtueset',
            name='title',
            field=models.TextField(default='Benjamin'),
            preserve_default=False,
        ),
    ]
