# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0004_auto_20170426_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtueStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_virtues', to=settings.AUTH_USER_MODEL)),
                ('virtue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_days', to='checklist.Virtue')),
            ],
        ),
    ]
