"""benjamin URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.views.generic.edit import CreateView

from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view
from rest_framework.authtoken import views

from benjamin.checklist.views import VirtueSetViewSet, VirtueDetailViewSet
from benjamin.registration.views import index

# Create a router and register viewsets
router = DefaultRouter()
router.register(r'virtues', VirtueDetailViewSet, base_name='virtue')
router.register(r'virtue_sets', VirtueSetViewSet, base_name='virtue_set')

# Add autogenerated schema view
schema_view = get_schema_view(title='Benjamin API')

urlpatterns = [
    url(r'^$', index),
    url(r'^api/', include(router.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^api-token-auth/$', views.obtain_auth_token),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^schema/', schema_view),
    url(r'^register/', CreateView.as_view(
        template_name='register.html',
        form_class=auth.forms.UserCreationForm,
        success_url='/'
    ), name='register'),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    # Provides the following patterns
    # ^accounts/login/$ [name='login']
    # ^accounts/logout/$ [name='logout']
    # ^accounts/password_change/$ [name='password_change']
    # ^accounts/password_change/done/$ [name='password_change_done']
    # ^accounts/password_reset/$ [name='password_reset']
    # ^accounts/password_reset/done/$ [name='password_reset_done']
    # ^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$ [name='password_reset_confirm']
    # ^accounts/reset/done/$ [name='password_reset_complete']
]
